name: Deploy Django App

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for EC2 access
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.41.254 >> ~/.ssh/known_hosts  # EC2 Public IP

      # Step 3: Deploy to EC2 (Pull code, install dependencies, migrate, collectstatic, restart services)
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@13.60.41.254 << 'EOF'
            # Navigate to project folder
            cd /home/ubuntu/aws-django

            # Pull the latest code from the repo
            git pull origin main  # Change to your deployment branch

            # Activate virtual environment
            source /home/ubuntu/aws-django/venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Run database migrations
            python manage.py migrate

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart Gunicorn to apply the new changes
            sudo systemctl restart gunicorn

            # Restart Nginx (if applicable) to reflect any changes
            sudo systemctl restart nginx
          EOF

      # Step 4: Notify of successful deployment (Optional)
      - name: Notify Success
        run: echo "Deployment Successful!"
