name: Deploy Django App

on:
  push:
    branches:
      - main # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for EC2 access
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          ssh-keyscan -H 16.171.5.253 >> ~/.ssh/known_hosts  # EC2 Public IP
      # Step 3: Set up ssh-agent (optional but recommended for handling private keys)
      - name: Set up ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Debug SSH Key
        run: |
          ls -lah ~/.ssh
          file ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa | head -n 5

      # Step 4: Deploy to EC2 (Pull code, install dependencies, migrate, collectstatic, restart services)
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@16.171.5.253 << 'EOF'
            # Navigate to project folder
            cd /home/ubuntu/aws-django

            # Pull the latest code from the repo
            git pull origin main  # Change to your deployment branch

            # Activate virtual environment
            source /home/ubuntu/aws-django/venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Run database migrations
            python manage.py migrate

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart Gunicorn to apply the new changes
            sudo systemctl restart gunicorn

            # Restart Nginx (if applicable) to reflect any changes
            sudo systemctl restart nginx
          EOF

      # Step 5: Notify of successful deployment (Optional)
      - name: Notify Success
        run: echo "Deployment Successful!"
